### ISSUE TITLE
importer/exporter storage component range work

### ISSUE THREAD

**Issue by StallEF** [Eco-Russian-Community/EcoConveyance#16]
Since server admins practice changing the range for the storage component, this causes the use of lines not to be used, so a fixed range 2 needs to be added.

```
var storage = this.GetComponent<PublicStorageComponent>();
this.GetComponent<LinkComponent>().Initialize(2);
storage.Initialize(2);
```

**Comment by Tavren** [comment]
currently they have
`this.GetComponent<LinkComponent>().Initialize(1);`
that not change anything as even without increased range, importer and exporter can be placed in standard radius
need to make additional check for adjacency
